# Supported funding platforms
# Each key supports one username/URL unless noted

# GitHub Sponsors — up to 4 usernames
github: [hasanharman]

# Other platforms — one username each
buy_me_a_coffee: hasanharman

# Uncomment and fill in any platforms you use:
# patreon: YOUR_USERNAME
# open_collective: YOUR_PROJECT
# liberapay: YOUR_USERNAME
# issuehunt: YOUR_USERNAME
# polar: YOUR_USERNAME
# tidelift: npm/isoshire
# community_bridge: YOUR_PROJECT
# lfx_crowdfunding: YOUR_PROJECT

