export const TILE_GROUPS = [
  {
    name: "Terrain",
    row: 0,
    tiles: [
      { col: 0, label: "Empty Grass" },
      { col: 1, label: "Tall Grass" },
      { col: 2, label: "Wildflower Meadow" },
      { col: 3, label: "Plowed Farmland" },
      { col: 4, label: "Wheat Field" },
      { col: 5, label: "Pumpkin Patch" },
      { col: 6, label: "Hay Bale" },
      { col: 7, label: "Dirt Path Straight" },
      { col: 8, label: "Dirt Path Curve" },
      { col: 9, label: "Dirt Path Crossroads" },
      { col: 10, label: "Cobblestone Path" },
      { col: 11, label: "Empty" },
    ],
  },
  {
    name: "Water & Bridges",
    row: 1,
    tiles: [
      { col: 0, label: "Calm Pond" },
      { col: 1, label: "River Straight" },
      { col: 2, label: "River Bend" },
      { col: 3, label: "River Fork" },
      { col: 4, label: "Small Wooden Bridge" },
      { col: 5, label: "Stone Bridge" },
      { col: 6, label: "Lily Pad Pond" },
      { col: 7, label: "Waterfall" },
      { col: 8, label: "Shallow Stream" },
      { col: 9, label: "Empty" },
      { col: 10, label: "Empty" },
      { col: 11, label: "Empty" },
    ],
  },
  {
    name: "Trees & Vegetation",
    row: 2,
    tiles: [
      { col: 0, label: "Single Oak Tree" },
      { col: 1, label: "Birch Trees Cluster" },
      { col: 2, label: "The Party Tree" },
      { col: 3, label: "Apple Orchard" },
      { col: 4, label: "Hedge Row" },
      { col: 5, label: "Vegetable Garden" },
      { col: 6, label: "Flowering Bush" },
      { col: 7, label: "Weeping Willow" },
      { col: 8, label: "Pine Tree" },
      { col: 9, label: "Mushroom Patch" },
      { col: 10, label: "Empty" },
      { col: 11, label: "Empty" },
    ],
  },
  {
    name: "Hobbit Holes",
    row: 3,
    tiles: [
      { col: 0, label: "Small Hobbit Hole" },
      { col: 1, label: "Medium Hobbit Hole" },
      { col: 2, label: "Bag End" },
      { col: 3, label: "Hobbit Hole w/ Fence" },
      { col: 4, label: "Hobbit Hole w/ Washing" },
      { col: 5, label: "Hobbit Hole w/ Mailbox" },
      { col: 6, label: "Empty" },
      { col: 7, label: "Empty" },
      { col: 8, label: "Empty" },
      { col: 9, label: "Empty" },
      { col: 10, label: "Empty" },
      { col: 11, label: "Empty" },
    ],
  },
  {
    name: "Buildings",
    row: 4,
    tiles: [
      { col: 0, label: "Green Dragon Inn" },
      { col: 1, label: "Hobbiton Mill" },
      { col: 2, label: "Market Stall" },
      { col: 3, label: "Bywater Bridge" },
      { col: 4, label: "Stone Well" },
      { col: 5, label: "Wooden Fence" },
      { col: 6, label: "Stone Wall" },
      { col: 7, label: "Lamp Post" },
      { col: 8, label: "Party Tent" },
      { col: 9, label: "Empty" },
      { col: 10, label: "Empty" },
      { col: 11, label: "Empty" },
    ],
  },
  {
    name: "Decorations",
    row: 5,
    tiles: [
      { col: 0, label: "Wooden Gate" },
      { col: 1, label: "Signpost" },
      { col: 2, label: "Bench" },
      { col: 3, label: "Barrel Stack" },
      { col: 4, label: "Cart w/ Produce" },
      { col: 5, label: "Campfire" },
      { col: 6, label: "Gandalf's Fireworks" },
      { col: 7, label: "Picnic Table" },
      { col: 8, label: "Empty" },
      { col: 9, label: "Empty" },
      { col: 10, label: "Empty" },
      { col: 11, label: "Empty" },
    ],
  },
] as const;

export const TEX_WIDTH = 12;
export const TEX_HEIGHT = 6;
export const SPRITE_TILE_W = 130;
export const SPRITE_TILE_H = 230;
